# -*- coding: utf-8 -*-

$LOAD_PATH.unshift 'lib'

require 'rubygems'
require 'bundler/setup'
require 'sequel'
require 'vnmgr'

begin
  require 'rspec/core/rake_task'
  RSpec::Core::RakeTask.new(:spec)
  task :default => :spec
rescue => LoadError
end

def connect(db_uri)
  Sequel.connect(db_uri)
end

def load_config(config_dir)
  Vnmgr::Configurations::Vnmgr.load(File.join(config_dir, "common.conf"), File.join(config_dir, "vnmgr.conf"))
end

def migrate(db_uri, to = nil)
  Sequel.extension :migration
  connect(db_uri)
  Sequel::Migrator.apply(Sequel::DATABASES.first, File.expand_path('../db/migrations', __FILE__), to)
end

namespace :db do
  db_uri = load_config("/etc/wakame-vnet/").db_uri
  task :init => [] do
    migrate(db_uri)
  end

  task :drop => [] do
    migrate(db_uri, 0)
  end

  task :dump => [] do
    Sequel.extension :schema_dumper
    db = connect(db_uri)
    puts db.dump_schema_migration
  end
end

namespace :test do
  db_uri = load_config("spec/config/").db_uri
  namespace :db do
    task :init => [] do
      migrate(db_uri)
    end

    task :drop => [] do
      migrate(db_uri, 0)
    end
  end
end
