inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'vnet/bin/**/*'
    - 'vnet/lib/**/*'
    - 'vnet/rack/**/*'
    - 'vnet/spec/**/*'
    - 'vnet/tools/**/*'
  Exclude:
    - 'vnet/db/**/*'
    - 'vnet/lib/vnet/node_api/proxies.rb'

Style/BlockDelimiters:
  Enabled: false
