inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'client/**/*.rb'
    - 'integration_test/**/*.rb'
    - 'vnet/rack/**/*'
    - 'vnet/spec/**/*.rb'
    - 'vnet/tools/*'
  Exclude:
    - 'vnet/db/migrations/*'
    - 'vnet/lib/vnet/node_api/proxies.rb'
    - 'vnet/vendor/**/*'

Style/BlockDelimiters:
  Enabled: false
