# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

VAGRANTFILE_API_VERSION = "2"

myconfig = YAML.load_file(File.expand_path("./config.yml", File.dirname(__FILE__)))

VAGRANT_BOX = "hansode/centos-6.5-x86_64"

vms = [
  {
    name: "vnmgr",
    networks: [
      { type: "hostonly", ip: "192.168.20.10" },
    ],
    sync_vnet: true,
  },
  {
    name: "vna1",
    networks: [
      { type: "hostonly", ip: "192.168.20.11" },
      { type: "intnet", name: "public_network1" },
    ],
    sync_vnet: true,
  },
  {
    name: "vna2",
    networks: [
      { type: "hostonly", ip: "192.168.20.12" },
      { type: "intnet", name: "public_network1" },
    ],
    sync_vnet: true,
  },
  {
    name: "vna3",
    networks: [
      { type: "hostonly", ip: "192.168.20.13" },
      { type: "intnet", name: "public_network2" },
    ],
    sync_vnet: true,
  },
  {
    name: "edge",
    networks: [
      { type: "hostonly", ip: "192.168.20.21" },
      { type: "intnet", name: "public_network1" },
      { type: "intnet", name: "public_network3" },
    ],
    sync_vnet: true,
  },
  {
    name: "legacy",
    networks: [
      { type: "hostonly", ip: "192.168.20.31" },
      { type: "intnet", name: "public_network3" },
    ]
  },
  {
    name: "router",
    networks: [
      { type: "hostonly", ip: "192.168.20.2" },
      { type: "intnet", name: "public_network1" },
      { type: "intnet", name: "public_network2" },
      { type: "intnet", name: "public_network3" },
    ]
  },
]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  vms.each do |vm|

    # only suuport virtualbox atm.
    config.vm.provider :virtualbox do |vb|
      vb.memory = vm[:memory] if vm[:memory]

      # https://github.com/mitchellh/vagrant/issues/1172
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end

    config.vm.define vm[:name] do |config|
      config.vm.box = vm[:box] || VAGRANT_BOX

      if vm[:sync_vnet]
        config.vm.synced_folder myconfig["vnet_path"], "/opt/axsh/openvnet/",
          type: "rsync", rsync__exclude: %w(.git/ vnet/.bundle vnet/vendor)
      end

      config.vm.hostname = vm[:name]
      vm[:networks].each.with_index do |network, index|

        nic_index = index + 2
        case network[:type]
        when "hostonly"
          config.vm.network :private_network, ip: network[:ip]
        when "intnet"
          config.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--nic#{nic_index}", network[:type]]
            vb.customize ["modifyvm", :id, "--intnet#{nic_index}", network[:name]]
          end
        end

        config.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--nicpromisc#{nic_index}", "allow-all"]
          # http://humbledown.org/virtualbox-intel-vlan-tag-stripping.xhtml
          vb.customize ["modifyvm", :id, "--nictype#{nic_index}", "Am79C973"]
        end
      end
    end
  end
end
