#!/bin/sh
set -e

user="vnet-webapi"
group="vnet-webapi"
logfile="/var/log/openvnet/webapi.log"

if ! getent group "$group" > /dev/null 2>&1 ; then
    addgroup --system "$group" --quiet
fi

if ! id "$user" > /dev/null 2>&1 ; then
    adduser --system --no-create-home \
	--ingroup "$group" --disabled-password \
	--shell /bin/false "$user"
fi

install -o "$user" -g "$group" -m 0755 "$logfile"
