
source "http://rubygems.org"

gem 'ffi-rzmq', "1.0.3"
gem "bit-struct", ">= 0.13.7"
gem "celluloid"
gem "celluloid-io"
gem "dcell"
gem "fuguta"
gem "ipaddress"
gem "json"
gem "mysql2"
gem "net-dhcp", ">= 1.1.1"
gem "net-dns"
gem "rack"
gem "rack-cors"
gem "racket", ">= 1.0.12", :git => 'https://github.com/axsh/racket.git'
gem "sequel", "4.8.0" # Updating to 4.23.0 broke the unit tests. Needs to be investigated.
gem "sequel_paranoia"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-hashfix"
gem "sinatra-browse", '0.3' # Updating to 0.5 broke the unit tests.
gem "unicorn"
gem "activesupport", '3.0.0' # Updating to 4.2.1 broke the unit tests.

# trema and build requirement gems
gem 'paper_house', '~>0.5.0'
gem 'rant', '>= 0.5.9', :git => 'https://github.com/axsh/rant.git'
gem 'trema', :git=>'https://github.com/axsh/trema.git', :branch=>'wakame-edge'

group :development, :test do
  gem "rake"
  gem "rspec"
  gem "rack-test"
  gem "fabrication", '2.9.8' # Updating to 2.13.2 broke the unit tests.
  gem 'database_cleaner'

  gem "coveralls"
  gem "vnet_api_client", path: File.dirname(File.expand_path('../../client/ruby/', __FILE__))

  gem "pry-byebug"
end
