# -*- coding: utf-8 -*-

module Vnet::Constants::Topology
  MODE_SIMPLE_OVERLAY = 'simple_overlay'
  MODE_SIMPLE_UNDERLAY = 'simple_underlay'

  MODES = [MODE_SIMPLE_OVERLAY,
           MODE_SIMPLE_UNDERLAY]

  MODES_WITH_OVERLAYS = [MODE_SIMPLE_UNDERLAY]
  MODES_WITH_UNDERLAYS = [MODE_SIMPLE_OVERLAY]

  MODES_WITH_DATAPATHS = [MODE_SIMPLE_UNDERLAY]
  MODES_WITH_NETWORKS = [MODE_SIMPLE_OVERLAY,
                         MODE_SIMPLE_UNDERLAY]
  MODES_WITH_SEGMENTS = [MODE_SIMPLE_OVERLAY,
                         MODE_SIMPLE_UNDERLAY]
  MODES_WITH_ROUTE_LINKS = [MODE_SIMPLE_OVERLAY]
  MODES_WITH_MAC_RANGE_GROUPS = [MODE_SIMPLE_UNDERLAY]
end
