datapaths:

  - uuid: dp-1
    node_id: vna1
    display_name: node1
    dpid: "0x0000aaaaaaaaaaaa"

  - uuid: dp-2
    node_id: vna2
    display_name: node2
    dpid: "0x0000bbbbbbbbbbbb"

  - uuid: dp-3
    node_id: vna3
    display_name: node3
    dpid: "0x0000cccccccccccc"

networks:

  - uuid: nw-public1
    display_name: public1
    ipv4_network: <%= public_ipv4_public1_network %>
    ipv4_prefix: <%= public_ipv4_public1_prefix %>
    domain_name: public
    network_mode: physical

  - uuid: nw-public2
    display_name: public2
    ipv4_network: <%= public_ipv4_public2_network %>
    ipv4_prefix: <%= public_ipv4_public2_prefix %>
    domain_name: public
    network_mode: physical

interfaces:

  - uuid: if-dp1eth0
    mode: host
    port_name: <%= physical_port %>
    owner_datapath_uuid: dp-1
    network_uuid: nw-public1
    mac_address: "02:01:00:00:00:01"
    ipv4_address: <%= dp1_ipv4_address %>

  - uuid: if-dp2eth0
    mode: host
    port_name: <%= physical_port %>
    owner_datapath_uuid: dp-2
    network_uuid: nw-public1
    mac_address: "02:01:00:00:00:02"
    ipv4_address: <%= dp2_ipv4_address %>

  - uuid: if-dp3eth0
    mode: host
    port_name: <%= physical_port %>
    owner_datapath_uuid: dp-3
    network_uuid: nw-public2
    mac_address: "02:01:00:00:00:03"
    ipv4_address: <%= dp3_ipv4_address %>

  - uuid: if-dhcppub1
    network_uuid: nw-public1
    mac_address: "02:00:00:00:01:11"
    ipv4_address: <%= public_ipv4_public1_dhcp_address %>
    mode: simulated

  - uuid: if-dhcppub2
    network_uuid: nw-public2
    mac_address: "02:00:00:00:01:22"
    ipv4_address: <%= public_ipv4_public2_dhcp_address %>
    mode: simulated

network_services:

  - uuid: ns-dhcppub1
    interface_uuid: if-dhcppub1
    mode: dhcp

  - uuid: ns-dhcppub2
    interface_uuid: if-dhcppub2
    mode: dhcp
